name: Test DinD

on: [workflow_dispatch]

jobs:
  build-ubuntu-2004:
    runs-on: self-hosted
    name: Build ubuntu_2004
    env:
      GITHUB_JOB: ${{ github.job }}

    steps:
      - name: Test kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: get po -A